version: '3.4'

services:
  invoicemartendbdemo:
    image: ${DOCKER_REGISTRY-}invoicemartendbdemo
    build:
      context: .
      dockerfile: InvoiceMartenDbDemo/Dockerfile

  postgresql:
    image: "clkao/postgres-plv8:latest"
    ports:
        - "5432:5432"

  rabbitmq:
    image: "rabbitmq:latest"
    ports:
        - "5672:5672"